from setuptools import setup

setup(
    name='ArrisCableModemMonitoring',
    version='0.01',
    packages=['venv.lib.python3.6.site-packages.bs4', 'venv.lib.python3.6.site-packages.bs4.tests',
              'venv.lib.python3.6.site-packages.bs4.builder', 'venv.lib.python3.6.site-packages.pip',
              'venv.lib.python3.6.site-packages.pip._vendor', 'venv.lib.python3.6.site-packages.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip._vendor.pep517',
              'venv.lib.python3.6.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip._internal', 'venv.lib.python3.6.site-packages.pip._internal.cli',
              'venv.lib.python3.6.site-packages.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip._internal.operations', 'venv.lib.python3.6.site-packages.idna',
              'venv.lib.python3.6.site-packages.pytz', 'venv.lib.python3.6.site-packages.certifi',
              'venv.lib.python3.6.site-packages.chardet', 'venv.lib.python3.6.site-packages.chardet.cli',
              'venv.lib.python3.6.site-packages.urllib3', 'venv.lib.python3.6.site-packages.urllib3.util',
              'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.dateutil', 'venv.lib.python3.6.site-packages.dateutil.tz',
              'venv.lib.python3.6.site-packages.dateutil.parser', 'venv.lib.python3.6.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.6.site-packages.influxdb', 'venv.lib.python3.6.site-packages.influxdb.tests',
              'venv.lib.python3.6.site-packages.influxdb.tests.influxdb08',
              'venv.lib.python3.6.site-packages.influxdb.tests.server_tests',
              'venv.lib.python3.6.site-packages.influxdb.influxdb08', 'venv.lib.python3.6.site-packages.logstash',
              'venv.lib.python3.6.site-packages.requests'],
    url='',
    license='',
    author='Raleigh Littles III',
    author_email='raleighlittles@gmail.com',
    description='A small collection of tools to monitor your Arris Surfboard cable modem using Grafana and Elasticsearch.'
)
